version: '3.9'
services:
  mongodb:
    image: mongo 
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    # networks:
    #   - minha-rede
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    # networks:
    #   - minha-rede
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend 
    # networks:
    #   - minha-rede
volumes:
  mongodb:
# networks:
#   minha-rede: